name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel

    - id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - name: Install dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
          pipenv install --deploy --dev

    - name: Test
      run: |
        make test

    - name: Publish
      run: |
        make publish

    - uses: actions/upload-artifact@v2
        with:
          name: monitor
          path: dist

    - name: Publish Test Report
      uses: ashley-taylor/junit-report-annotations-action@1.3
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
      if: always()

