name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade pipenv wheel
        make setup
    - name: Test
      run: |
        make test
    - name: Publish
      run: |
        make publish
    - uses: actions/upload-artifact@v2
      with:
        name: pi-build-monitor
        path: dist/pi-build-monitor-0.1.0.tar.gz