jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      -
        name: "Install pipenv"
        run: "python -m pip install --upgrade pipenv wheel\n"
      -
        id: cache-pipenv
        uses: actions/cache@v1
        with:
          key: "${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}"
          path: ~/.local/share/virtualenvs
      -
        if: "steps.cache-pipenv.outputs.cache-hit != 'true'"
        name: "Install dependencies"
        run: "pipenv install --deploy --dev\n"
      -
        name: Test
        run: "make test\n"
      -
        name: Publish
        run: "make publish\n"
      -
        uses: actions/upload-artifact@v2
        with:
          name: monitor
          path: dist
      -
        if: always()
        name: "Publish Test Report"
        uses: ashley-taylor/junit-report-annotations-action@1.3
        with:
          access-token: "${{ secrets.GITHUB_TOKEN }}"
name: CI
true:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
